# Generated by Django 4.2.20 on 2025-03-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_visitante_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='acao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
