# Generated by Django 5.1.7 on 2025-04-07 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accesslog_acao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicialPresença',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_entrada', models.DateTimeField(auto_now_add=True)),
                ('horario_saida', models.DateTimeField(blank=True, null=True)),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.policial')),
            ],
        ),
        migrations.CreateModel(
            name='PresencaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.policial')),
            ],
        ),
        migrations.CreateModel(
            name='Procurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('visitante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.visitante')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoPrisao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(default='Deserção', max_length=255)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.policial')),
            ],
        ),
    ]
