# Generated by Django 5.1.7 on 2025-04-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_solicitacaoprisao_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PolicialPresença',
            new_name='PolicialPresenca',
        ),
    ]
